### PR TITLE
Add the username option to RedisSettings

### PR DESCRIPTION
**Pull request by ula**
This PR adds the ability to pass the `username` option to the Redis connection

### CODE REVIEW

**Comment by samuelcolvin** [comment]
great, thank you very much.

**Comment by dnikolayev** [comment]
Hey, Guys!
Will there be a release with this fix soon? ;)

O.23a doesn't have this, right?
Good that I found this PR, as I wanted to propose the fix already. Having issues with redis6 out of the box default conf because of username :(

**Comment by samuelcolvin** [comment]
I'll try to get to this soon, sorry for the delay.

**Comment by dnikolayev** [comment]
> I'll try to get to this soon, sorry for the delay.

Thanks a lot!
In my case it was hard to find the source as the job enqueues were just passing without any error or doing anything :)

Arq is great!
Thanks for your work!

**Pull request merged**
