### PR TITLE
allow unix-socket connection in RedisSettings (socket_address)

### PR DESCRIPTION
**Pull request by lazToum**
following the recommendation in https://github.com/samuelcolvin/arq/pull/209#issuecomment-826137334

### CODE REVIEW

**Comment by samuelcolvin** [comment]
I'm wondering how this will interact with #259? I want to get that merged before the next release.

**Comment by lazToum** [comment]
It will probably need a few minor modifications. (adding a `unix_socket_path` init argument according to https://github.com/aio-libs/aioredis-py/blob/56d6b325ee246a3eb0fc8bb6803247c86bb2f494/aioredis/client.py#L845
Of course, I can work on it again later, after #259 is merged.

**Comment by samuelcolvin** [comment]
#259 is merged, if you still want to work on this, I'd be happy to review an update.

**Comment by lazToum** [comment]
Nice!
currently waiting for https://github.com/redis/redis-py/pull/2046 (for UnixDomainSocketConnection) and https://github.com/yahoo/redislite/pull/153 (for redislite/testing on python 3.10)

**Comment by samuelcolvin** [comment]
There's lots of conflicts here, you'll need to rebase/merge with master.

**Pull request closed without merging**
