### PR TITLE
Added the SSL option for RedisSettings dataclass

### PR DESCRIPTION
**Pull request by Relrin**
This PR adds and opportunity to specify SSL options for making an encrypted connection between the client and Redis nodes.

### CODE REVIEW

**Comment by samuelcolvin** [comment]
looks good, please could you fix tess.

**Comment by samuelcolvin** [comment]
also, could you add a new line to `HISTORY.rst`.

**Comment by Relrin** [comment]
Sure. Give me a couple of minutes.

**Comment by Relrin** [comment]
Everything is fixed.

**Comment by samuelcolvin** [comment]
thank you very much, deploying now.

**Pull request merged**
